apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: devflow
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: devflow
    app.kubernetes.io/managed-by: kubectl
data:
  SPRING_PROFILES_ACTIVE: "dev"
  SERVER_PORT: "8080"
  DB_URL: "jdbc:postgresql://<RDS_HOST>:5432/deflow_db"
  JWT_EXPIRATION: "3600000"
