apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: devflow
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: devflow
    app.kubernetes.io/managed-by: kubectl
type: Opaque
stringData:
  DB_USERNAME: "<DB_USERNAME>"
  DB_PASSWORD: "<DB_PASSWORD>"
  JWT_SECRET: "<JWT_SECRET>"
