apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: devflow
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
  labels:
    app: backend
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: devflow
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
