apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: devflow
  labels:
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: devflow
    app.kubernetes.io/managed-by: kubectl
automountServiceAccountToken: false
