apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: devflow
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
  labels:
    app: frontend
    app.kubernetes.io/name: frontend
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: devflow
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
