apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-secret
  namespace: devflow
  labels:
    app.kubernetes.io/name: gitlab-registry-secret
    app.kubernetes.io/component: registry-credentials
    app.kubernetes.io/part-of: devflow
    app.kubernetes.io/managed-by: kubectl
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <DOCKER_CONFIG_JSON>
