apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: aws-load-balancer-controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/version: v2.14.1
    app.kubernetes.io/part-of: devflow
    app.kubernetes.io/managed-by: kubectl
  annotations:
    eks.amazonaws.com/role-arn: "<ALB_CONTROLLER_IAM_ROLE_ARN>"
    eks.amazonaws.com/sts-regional-endpoints: "true"
automountServiceAccountToken: true
