apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-deployer
  namespace: devflow
  labels:
    app.kubernetes.io/name: gitlab-deployer
    app.kubernetes.io/component: ci-deployer
    app.kubernetes.io/part-of: devflow
    app.kubernetes.io/managed-by: kubectl
